spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/luvin
    username: postgres
    password: 비밀번호

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080