-- 설문 v2(빵 유형 채점/분류) 신규 테이블. 기존 34개 테이블은 그대로 두고(ddl-auto:update가 계속 관리),
-- 여기서는 nullable column/new table만 추가하는 expand-only migration이다.
-- luvin-survey-change-plan/BACKEND_CHANGES.md 7절 DB 모델 제안을 그대로 반영한다.
--
-- 주의: Spring Boot는 Flyway를 Hibernate ddl-auto보다 먼저 실행한다. 완전히 빈 DB(CI의 매 실행마다
-- 새로 뜨는 postgres 컨테이너 포함)에서는 이 시점에 users/ai_seasons 등 레거시 테이블이 아직 없으므로,
-- 그 테이블을 향한 REFERENCES나 ALTER TABLE은 여기 두지 않는다. users.latest_survey_result_id와
-- ai_seasons.survey_result_id는 각각 User/AiSeason 엔티티의 신규 필드로 선언해 ddl-auto:update가
-- Flyway 실행 "이후"에 추가하게 한다(FK 제약은 없이 애플리케이션 레벨로만 참조 무결성을 지킨다).

CREATE TABLE survey_definitions (
    id                      UUID PRIMARY KEY,
    survey_version          VARCHAR(100) NOT NULL,
    scoring_version         VARCHAR(100) NOT NULL,
    classification_version VARCHAR(100) NOT NULL,
    config_hash             VARCHAR(64) NOT NULL,
    config_json             JSONB NOT NULL,
    status                  VARCHAR(20) NOT NULL,
    created_at              TIMESTAMP NOT NULL,
    CONSTRAINT uk_survey_definitions_versions UNIQUE (survey_version, scoring_version, classification_version)
);

CREATE TABLE survey_submissions (
    id                    UUID PRIMARY KEY,
    member_id             BIGINT NOT NULL,
    definition_id         UUID NOT NULL REFERENCES survey_definitions (id),
    client_submission_id  UUID NOT NULL,
    request_hash          VARCHAR(64) NOT NULL,
    submitted_at          TIMESTAMP NOT NULL,
    CONSTRAINT uk_survey_submissions_member_client UNIQUE (member_id, client_submission_id)
);

CREATE TABLE survey_submission_answers (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id  UUID NOT NULL REFERENCES survey_submissions (id),
    question_code  VARCHAR(20) NOT NULL,
    answer_code    VARCHAR(20) NOT NULL,
    CONSTRAINT uk_survey_submission_answers UNIQUE (submission_id, question_code)
);

CREATE TABLE survey_results (
    id                    UUID PRIMARY KEY,
    submission_id         UUID NOT NULL UNIQUE REFERENCES survey_submissions (id),
    core_scores           JSONB NOT NULL,
    auxiliary_scores      JSONB NOT NULL,
    evidence_stats        JSONB NOT NULL,
    distances             JSONB NOT NULL,
    primary_type          VARCHAR(50) NOT NULL,
    secondary_type        VARCHAR(50) NOT NULL,
    mixed                 BOOLEAN NOT NULL,
    poor_fit              BOOLEAN NOT NULL,
    tie                   BOOLEAN NOT NULL,
    top_two_gap           NUMERIC(12, 6) NOT NULL,
    explanation_evidence  JSONB NOT NULL,
    created_at            TIMESTAMP NOT NULL
);

CREATE TABLE ai_season_creation_inputs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id         BIGINT NOT NULL UNIQUE,
    survey_result_id  UUID NOT NULL REFERENCES survey_results (id),
    profile_json      JSONB NOT NULL,
    request_hash      VARCHAR(64) NOT NULL,
    idempotency_key   UUID NOT NULL,
    status            VARCHAR(20) NOT NULL,
    created_at        TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP NOT NULL
);
